name: Check

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    check:
        strategy:
            matrix:
                node_version: ['20.8.0']
        runs-on: ubuntu-latest
        container: node:${{matrix.node_version}}
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js ${{matrix.node_version}}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{matrix.node_version}}
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm format:check
            - run: pnpm lint
